#set image(height: 4cm)

In industriellen Fertigungsprozessen ist eine zuverlässige Qualitätssicherung eine grundlegende Voraussetzung für die Funktionsfähigkeit, Zuverlässigkeit und Wirtschaftlichkeit technischer Produkte. Zur frühzeitigen Erkennung von Abweichungen vom Sollzustand, im Folgenden als Anomalien bezeichnet, kommen häufig optische bzw. zerstörungsfreie Prüfverfahren zum Einsatz. Diese Anomalien äußern sich beispielsweise in geometrischen Verformungen, Oberflächenfehlern, Materialeinschlüssen, Verschmutzungen oder Farbabweichungen. In der industriellen Praxis erfolgt die visuelle Qualitätsprüfung vielfach durch geschultes Fachpersonal, wodurch subjektive Bewertungseinflüsse sowie eine eingeschränkte Reproduzierbarkeit der Prüfergebnisse entstehen können.

Zur Reduktion dieser Einschränkungen gewinnen automatisierte Prüfverfahren auf Basis des @ML zunehmend an Bedeutung. @ML ist ein Teilgebiet der @KI, bei dem Algorithmen aus Daten relevante Muster und Strukturen selbstständig erlernen. Insbesondere Verfahren der_ @AD _aus dem Bereich des _Unsupervised Learnings_ bieten für industrielle Anwendungen wesentliche Vorteile, da sie ohne explizit gelabelte Fehlerdaten auskommen. Dies ist insbesondere in realen Produktionsumgebungen von hoher Relevanz, da fehlerhafte Bauteile häufig nur in begrenzter Anzahl oder nicht in ausreichender Variationsbreite verfügbar sind. Die hohe Vielfalt möglicher Fehlerbilder führt zudem zu einem erheblichen manuellen Annotierungsaufwand und schränkt den praktischen Einsatz überwachter Lernverfahren ein.

Die optische Qualitätsprüfung basiert in der Regel auf der Auswertung von Kamerabildern. Um eine robuste und vergleichbare Analyse zu ermöglichen, wird häufig eine definierte und reproduzierbare Ausrichtung der Prüflinge angestrebt. Bei komplexen Bauteilen mit mehreren funktional relevanten Oberflächen oder rotationsabhängigen Merkmalen ist eine vollständige Inspektion aus einer einzelnen Perspektive jedoch nicht ausreichend. Perspektivbedingte Verdeckungen können dazu führen, dass relevante Anomalien nicht zuverlässig erfasst werden. In solchen Fällen ist eine mehrperspektivische Erfassung erforderlich, um eine vollständige visuelle Abdeckung des Bauteils sicherzustellen.

Im Rahmen dieser Studienarbeit wird die optische Qualitätsprüfung eines_ @SAC _der Phoenix Contact GmbH & Co. KG betrachtet. Hierfür kommt eine speziell entwickelte Prüfvorrichtung zum Einsatz, in welche der Stecker eingeführt und anschließend durch ein Kamerasystem mit insgesamt zwölf Kameras aus unterschiedlichen Blickwinkeln aufgenommen wird. Diese Multi‑View-Erfassung ermöglicht eine vollständige Rundum‑Inspektion des Steckers und stellt sicher, dass sämtliche relevanten Sichtbereiche abgebildet werden. Aufgrund der komplexen Geometrie des Produkts sowie der Vielzahl potenzieller Fehlerbilder, darunter Materialüberschüsse, Unterspritzungen, Verschmutzungen, Kontaktverformungen oder Beschädigungen am Kabel, ist eine zuverlässige Bewertung einzelner Bildansichten allein nicht ausreichend.

#figure(image("../98_assets/Product.png"),caption: [Sensor Actuator Cabel]) <Product>

Eine zentrale Herausforderung dieses Anwendungsfalls liegt in der hohen Varianz möglicher Anomalien bei gleichzeitig begrenzter Verfügbarkeit realer Schlechtteile. Viele Fehler treten selten auf oder sind zum Zeitpunkt der Modellentwicklung nicht in ausreichender Anzahl vorhanden. Dies erschwert den Aufbau repräsentativer Datensätze und führt zu einem hohen manuellen Labeling‑Aufwand. Ziel dieser Studienarbeit ist es daher, zu untersuchen, inwieweit unsupervised Anomalieerkennungsverfahren in Kombination mit Multi‑View-Informationen geeignet sind, eine robuste und skalierbare optische Qualitätsprüfung für_ @SAC _zu realisieren. Ergänzend wird analysiert, in welchem Maße _Active‑Learning_‑Ansätze dazu beitragen können, den erforderlichen Annotierungsaufwand zu reduzieren und die Modellleistung gezielt zu verbessern. Die gewonnenen Erkenntnisse dienen als fundierte Grundlage für die Auswahl geeigneter Methoden und Architekturen im Rahmen einer weiterführenden Bachelorarbeit.