Ziel dieser Studienarbeit war die methodische Untersuchung der Eignung mehrperspektivischer Bilddaten für die bildbasierte unsupervised Anomaly Detection im industriellen Umfeld. Am Beispiel der optischen Qualitätsprüfung von Sensor‑Aktor‑Kabeln wurden die besonderen Herausforderungen analysiert, die sich aus der Kombination von Multi‑View‑Erfassung, stark unbalancierter Datenlage und begrenzter Verfügbarkeit realer Fehlerdaten ergeben. Der Fokus lag dabei ausdrücklich auf der methodischen Einordnung und nicht auf der Entwicklung einer produktiven Prüf‑ oder Entscheidungslösung.

Die Analyse der zugrunde liegenden Daten zeigte, dass mehrperspektivische Bildaufnahmen ein hohes Potenzial zur Erhöhung der Erkennungsrobustheit besitzen, da perspektivabhängige Verdeckungen reduziert und lokal begrenzte Anomalien zuverlässiger erfasst werden können. Gleichzeitig führt die Multi‑View‑Erfassung zu einer erhöhten Daten‑ und Modellkomplexität. Insbesondere die Heterogenität der einzelnen Kameraperspektiven erfordert eine konsistente Vorverarbeitung sowie eine strukturierte Organisation der Daten über alle Verarbeitungsschritte hinweg.

Aufbauend darauf wurden konzeptionelle Ansätze der unsupervised Anomaly Detection und Strategien zur Integration mehrperspektivischer Informationen untersucht. Die betrachteten Verfahren modellieren den Normalzustand ausschließlich anhand fehlerfreier Referenzdaten und nutzen tiefenlernbasierte Merkmalsextraktion. Dabei zeigte sich, dass insbesondere späte Fusionsansätze eine robuste und zugleich praktikable Möglichkeit darstellen, Informationen aus mehreren Perspektiven zu integrieren, ohne die Modellkomplexität unverhältnismäßig zu erhöhen.

Die Evaluation der Ansätze diente primär der vergleichenden methodischen Einordnung unter realistischen industriellen Randbedingungen. Scorebasierte Metriken wie die AUROC erwiesen sich als grundsätzlich geeignet, um unterschiedliche Modellierungs‑ und Fusionsstrategien zu vergleichen. Gleichzeitig wurde deutlich, dass die Aussagekraft der Ergebnisse durch die starke Klassenunbalance und die begrenzte Abdeckung realer Fehlerbilder eingeschränkt ist und eine kontextbezogene Interpretation erfordert.

Zusammenfassend zeigt die Studienarbeit, dass unsupervised Anomaly Detection in Kombination mit mehrperspektivischer Bildaufnahme ein vielversprechender Ansatz für industrielle Qualitätsprüfungen ist. Der Mehrwert der Multi‑View‑Information liegt weniger in einzelnen Kennzahlen als in einer erhöhten Robustheit gegenüber perspektivabhängigen Effekten. Voraussetzung hierfür ist jedoch eine durchgängige methodische Konsistenz entlang der gesamten Verarbeitungskette.

Der Ausblick dieser Arbeit richtet sich auf eine weiterführende Bachelorarbeit. Zukünftige Arbeiten sollten eine vertiefte empirische Evaluation verschiedener Modellarchitekturen auf einer erweiterten Datenbasis durchführen. Darüber hinaus bietet der Einsatz von Active‑Learning‑Strategien ein erhebliches Potenzial zur Reduktion des manuellen Annotierungsaufwands. Weitere Forschungsperspektiven ergeben sich aus der Untersuchung adaptiver Multi‑View‑Fusionsstrategien sowie der Übertragbarkeit der gewonnenen Erkenntnisse auf andere industrielle Anwendungsfälle.