#set image(height: 7.5cm)

In dieser Arbeit wird das @CRISP-DM Modell als methodisches Vorgehensmodell eingesetzt, um den Versuchsaufbau strukturiert, nachvollziehbar und reproduzierbar auszugestalten. Der methodische Fokus liegt zunächst auf der systematischen Identifikation und Analyse der für das Gesamtproblem relevanten Fragestellungen, während in nachfolgenden Schritten sukzessive weniger kritische Teilaspekte berücksichtigt werden. Das @CRISP-DM Modell gliedert sich hierbei in die sechs Phasen _Business Understanding_, _Data Understanding_, _Data Preparation_, _Modeling_, _Evaluation_ und _Deployment_.

#figure(image("../98_assets/methodical_approach.svg"),caption: [Cross-Industry Standard Process for Data Mining]) <Product>

Das Vorgehen ist explizit iterativ angelegt, wobei insbesondere die Phasen _Modeling_ und _Evaluation_ mehrfach durchlaufen werden. Die in den einzelnen Iterationen gewonnenen Erkenntnisse werden gezielt zur kontinuierlichen Anpassung der Datenaufbereitung sowie zur Auswahl und Parametrisierung der eingesetzten Modelle genutzt. Auf diese Weise entsteht ein schrittweiser Entwicklungs‑ und Optimierungsprozess, durch den die erarbeitete Lösung fortlaufend an die spezifischen Anforderungen der realen Produktionsumgebung für_ @SAC _angenähert wird.
Aufgrund seiner datengetriebenen und zyklischen Struktur eignet sich das @CRISP-DM Modell in besonderem Maße für die Bearbeitung der bildbasierten, unüberwachten Multi‑View‑Anomalieerkennung in dieser Arbeit. Zu Beginn werden grundlegende methodische Entscheidungen getroffen, insbesondere hinsichtlich der Analyse und Vorverarbeitung der Bilddaten aus mehreren Kameraperspektiven sowie der Auswahl geeigneter Verfahren zur_ @AD. _Darauf aufbauend erfolgt eine sukzessive Verfeinerung der Lösung in mehreren Iterationsschleifen, in denen unterschiedliche Modelle implementiert, systematisch miteinander verglichen und anhand definierter Evaluationsmetriken bewertet werden.

Die im Rahmen dieses iterativen Prozesses entwickelte Lösung wird abschließend umfassend analysiert und hinsichtlich ihrer Leistungsfähigkeit diskutiert. Darüber hinaus werden bestehende Limitationen der vorgestellten Methodik aufgezeigt sowie mögliche zukünftige Optimierungsansätze erörtert, insbesondere im Hinblick auf den Einsatz von Active‑Learning‑Strategien zur gezielten Einbindung menschlichen Feedbacks.