Die automatisierte visuelle Qualitätsprüfung industrieller Produkte basiert zunehmend auf der Kombination klassischer Bildverarbeitung mit Methoden des @ML. Ziel solcher Systeme ist es, Abweichungen vom erwarteten Normalzustand eines Bauteils zuverlässig zu erkennen. Diese Abweichungen werden im Folgenden als Anomalien bezeichnet und können sich unter anderem in Form von geometrischen Verformungen, Oberflächenfehlern, Materialeinschlüssen, Verschmutzungen oder Farbabweichungen äußern.

Im Unterschied zu klassischen Klassifikationsansätzen, bei denen alle relevanten Fehlerklassen im Vorfeld bekannt und explizit annotiert sein müssen, verfolgt die _ @AD _einen grundsätzlich anderen Ansatz. Statt einer Zuordnung zu vordefinierten Klassen steht hier die Identifikation von Abweichungen vom erlernten Normalzustand im Vordergrund. Dieser Ansatz ist insbesondere für industrielle Produktionsumgebungen geeignet, da viele Fehlerbilder nur selten auftreten, eine hohe visuelle Varianz aufweisen oder zum Zeitpunkt der Modellentwicklung nicht in ausreichender Anzahl verfügbar sind.

Ein zentrales Unterscheidungsmerkmal bildbasierter_ @AD _-verfahren ist das zugrunde liegende Lernparadigma. Während Verfahren des _Supervised Learnings_ auf vollständig gelabelte Datensätze angewiesen sind, modellieren Ansätze der _Unsupervised @AD _den Normalzustand eines Bauteils ausschließlich anhand fehlerfreier Referenzdaten. Anomalien werden anschließend als signifikante Abweichungen von diesem erlernten Normalverhalten identifiziert. Dadurch wird der manuelle Annotierungsaufwand deutlich reduziert und gleichzeitig die Erkennung bislang unbekannter Fehlerarten ermöglicht.

Moderne bildbasierte _ @AD _-verfahren greifen häufig auf tiefenlernbasierte Merkmalsextraktion zurück, um visuelle Strukturen auf unterschiedlichen Abstraktionsebenen abzubilden. Hierbei kommen in der Regel _ @CNN _ zum Einsatz, die entweder vollständig trainiert oder als vortrainierte _Feature_‑Extraktoren verwendet werden. Die extrahierten Merkmale dienen nicht der direkten Klassifikation, sondern stellen kompakte Repräsentationen der Bildinhalte dar, auf deren Basis Abweichungen vom Normalzustand quantifiziert werden können.

Ein verbreiteter Ansatz besteht darin, Bilddaten in kleinere lokale Regionen zu unterteilen und diese separat zu analysieren. Durch diese _patch_‑basierte Betrachtung können auch lokal begrenzte Defekte erkannt werden, die im globalen Bildkontext nur schwer sichtbar sind. Die Bewertung erfolgt typischerweise über einen Anomaliescore, der angibt, wie stark ein Bild oder ein Bildbereich vom erlernten Normalzustand abweicht. Auf diese Weise lassen sich sowohl globale als auch lokal begrenzte Anomalien identifizieren.

Die in diesem Abschnitt dargestellten Grundlagen bilden die theoretische Basis für die nachfolgenden Kapitel. Aufbauend darauf wird in Abschnitt 2.3 die Nutzung mehrperspektivischer Bilddaten im Rahmen der Multi‑View‑Bildanalyse betrachtet. Abschnitt 2.4 gibt anschließend einen Überblick über den aktuellen Stand der Forschung im Bereich der bildbasierten_ @AD _, bevor in Abschnitt 2.5 die zur Bewertung der Verfahren eingesetzten Metriken erläutert werden.