Bei der optischen Qualitätsprüfung komplexer industrieller Bauteile ist eine vollständige visuelle Erfassung aus einer einzelnen Kameraperspektive häufig nicht ausreichend. Abhängig von Geometrie, Oberflächenbeschaffenheit und räumlicher Ausrichtung des Prüflings können relevante Bereiche verdeckt sein oder nur eingeschränkt erfasst werden. Insbesondere bei dreidimensional ausgeprägten oder rotationssymmetrischen Objekten besteht die Gefahr, dass Anomalien lediglich aus bestimmten Blickwinkeln sichtbar sind und bei einer monoperspektivischen Analyse unentdeckt bleiben.

Die Multi‑View‑Bildanalyse adressiert diese Einschränkungen durch die gleichzeitige Nutzung mehrerer Bildaufnahmen desselben Objekts aus unterschiedlichen Perspektiven. Ziel ist es, die in den einzelnen Ansichten enthaltenen komplementären Informationen so zu kombinieren, dass eine möglichst vollständige und robuste Repräsentation des Prüflings entsteht. Durch die Berücksichtigung mehrerer Sichtwinkel lassen sich Verdeckungen reduzieren und perspektivabhängige Unterschiede ausgleichen. Für die bildbasierte_ @AD _ergibt sich daraus der Vorteil, dass potenzielle Fehler nicht mehr ausschließlich von einer einzelnen Ansicht abhängig sind.

Die Nutzung mehrerer Perspektiven führt jedoch auch zu zusätzlichen Herausforderungen. Die einzelnen Bildansichten können sich hinsichtlich Perspektive, Beleuchtung, Abbildungsmaßstab und Hintergrund unterscheiden, was eine konsistente Interpretation der Bildinformationen erschwert. Darüber hinaus stellt sich die Frage, wie die Informationen der verschiedenen _Views_ sinnvoll miteinander verknüpft werden können, ohne Redundanzen zu verstärken oder relevante Details zu verlieren. Eine zentrale Rolle spielt hierbei die Wahl einer geeigneten Strategie zur Fusion der Multi‑View‑Informationen.

Grundsätzlich lassen sich Multi‑View‑Ansätze anhand des Zeitpunkts der Informationsfusion unterscheiden. Bei einer frühen Fusion _(Early Fusion)_ werden die Bilddaten oder extrahierten Merkmale der einzelnen Perspektiven bereits in einem frühen Verarbeitungsschritt zusammengeführt und gemeinsam analysiert. Demgegenüber erfolgt bei einer späten Fusion _(Late Fusion)_ zunächst eine separate Auswertung jeder Ansicht, deren Ergebnisse erst in einem nachgelagerten Schritt kombiniert werden. Zwischen diesen beiden Ansätzen existieren hybride Strategien, bei denen eine partielle Zusammenführung auf Zwischenebenen erfolgt. Die Wahl der Fusionsstrategie beeinflusst unter anderem den Rechenaufwand, die Robustheit gegenüber fehlerhaften Einzelansichten sowie die Interpretierbarkeit der Ergebnisse.

Im Kontext der _unsupervised @AD _ergeben sich durch die Multi‑View‑Analyse zusätzliche Potenziale, da Anomalien über mehrere Perspektiven hinweg konsistent bestätigt oder räumlich eingegrenzt werden können. Gleichzeitig steigt jedoch die Komplexität der Datenverarbeitung sowie der Modellarchitektur. Insbesondere bei der Modellierung des Normalzustands ist daher sorgfältig abzuwägen, in welcher Form die zusätzlichen Informationen genutzt werden können, ohne die Lernfähigkeit des Modells negativ zu beeinflussen oder unerwünschte Abhängigkeiten zwischen den einzelnen Ansichten zu erzeugen.

Die Multi‑View‑Bildanalyse stellt somit eine wesentliche Erweiterung klassischer bildbasierter Prüfverfahren dar und bildet die Grundlage für die in dieser Arbeit betrachteten Ansätze zur _@AD _. Aufbauend auf den hier beschriebenen Konzepten werden im folgenden Abschnitt relevante Forschungsarbeiten vorgestellt, die sich mit der Nutzung mehrperspektivischer Bilddaten im Kontext der visuellen _@AD _befassen.