Die vorangegangenen Kapitel haben gezeigt, dass die bildbasierte unsupervised Anomaly Detection im industriellen Umfeld mit spezifischen methodischen Herausforderungen verbunden ist. Diese resultieren insbesondere aus der hohen Varianz realer Fehlerbilder, der stark unbalancierten Datenverteilung sowie der zunehmenden Komplexität moderner Bildaufnahmesysteme. Im Anwendungsfall der Sensor‑Aktor‑Kabelproduktion (Sensor Actuator Cable, SAC) treten diese Faktoren in kombinierter Form auf und prägen maßgeblich die Anforderungen an eine robuste visuelle Qualitätsprüfung.

Im betrachteten Produktionsprozess werden die Steckverbinder mithilfe eines fest installierten Multi‑View‑Kamerasystems aus insgesamt zwölf unterschiedlichen Blickwinkeln erfasst. Ziel dieser Erfassungsstrategie ist eine möglichst vollständige visuelle Abdeckung aller funktionsrelevanten Oberflächenbereiche des Prüflings. Die mehrperspektivische Aufnahme führt jedoch zu einer erheblichen Erhöhung der Datenkomplexität, da pro Bauteil eine Vielzahl heterogener Bildansichten vorliegt. Diese unterscheiden sich unter anderem hinsichtlich Perspektive, Beleuchtung, Abbildungsmaßstab und sichtbarer Detailtiefe. Eine rein monoperspektivische Analyse ist unter diesen Bedingungen nicht ausreichend geeignet, da visuelle Anomalien häufig nur aus bestimmten Blickwinkeln erkennbar sind und sich perspektivabhängig unterschiedlich manifestieren.

Eine weitere zentrale Herausforderung ergibt sich aus der eingeschränkten Verfügbarkeit realer Schlechtteile. Viele relevante Defektarten treten im Produktionsbetrieb nur selten auf oder stehen während der Entwicklungsphase eines Prüfsystems nicht in ausreichender Anzahl zur Verfügung. Gleichzeitig weisen die vorhandenen Fehlerbilder eine hohe visuelle Variabilität auf, wodurch eine umfassende manuelle Annotation aller potenziellen Anomalien mit erheblichem Aufwand verbunden wäre. Vor diesem Hintergrund sind klassische überwachte Lernverfahren nur eingeschränkt praktikabel, da sie auf umfangreiche, repräsentative und vollständig gelabelte Datensätze angewiesen sind. Stattdessen bieten unsupervised Anomalieerkennungsverfahren ein hohes Potenzial, da sie den Normalzustand des Produkts ausschließlich auf Basis fehlerfreier Referenzdaten modellieren und Abweichungen von diesem Normalverhalten identifizieren.

Die übergeordnete Problemstellung dieser Studienarbeit besteht darin, zu untersuchen, wie mehrperspektivische Bilddaten eines industriellen Bauteils so strukturiert, aufbereitet und ausgewertet werden können, dass eine robuste unsupervised Anomaly Detection auch unter realistischen industriellen Randbedingungen möglich ist. Dabei ist insbesondere zu analysieren, welchen Beitrag die Integration von Multi‑View‑Informationen zur Stabilität und Aussagekraft der Erkennung leistet und welche methodischen Entscheidungen hierbei von zentraler Bedeutung sind.

Aus dieser Problemstellung ergeben sich mehrere Zielsetzungen. Erstens soll ein fundiertes Verständnis für die spezifischen Anforderungen, Potenziale und Limitationen der Multi‑View‑basierten unsupervised Anomaly Detection im industriellen Kontext erarbeitet werden. Zweitens werden unterschiedliche konzeptionelle Strategien zur Nutzung mehrperspektivischer Bilddaten analysiert, insbesondere im Hinblick auf mono‑ und multiview‑basierte Auswertungsansätze sowie verschiedene Formen der Informationsfusion. Drittens wird explorativ untersucht, inwieweit Active‑Learning‑Strategien perspektivisch dazu beitragen können, den manuellen Annotierungsaufwand zu reduzieren, indem gezielt besonders informative Datenpunkte für eine nachgelagerte Bewertung identifiziert werden.

Die Studienarbeit ist dabei ausdrücklich nicht auf einen produktiven Einsatz der betrachteten Ansätze ausgerichtet. Der Fokus liegt vielmehr auf der methodischen Analyse, Bewertung und kritischen Reflexion unterschiedlicher Vorgehensweisen. Die gewonnenen Erkenntnisse dienen als Entscheidungsgrundlage für die Auswahl geeigneter Modellarchitekturen, Datenstrategien und Evaluationskonzepte im Rahmen einer weiterführenden Bachelorarbeit. Entsprechend werden in den folgenden Abschnitten der Versuchsaufbau, die Datengrundlage sowie die Evaluationsmethodik transparent und nachvollziehbar dargestellt, um eine reproduzierbare Basis für zukünftige Arbeiten zu schaffen.