Die im Rahmen dieser Studienarbeit verwendete Datengrundlage besteht aus industriellen Bilddaten der optischen Qualitätsprüfung von Sensor‑Aktor‑Kabeln (Sensor Actuator Cable, SAC) aus einer realen Produktionsumgebung. Die Bilddaten wurden mithilfe eines speziell für diesen Anwendungsfall entwickelten Multi‑View‑Kamerasystems erfasst, das eine vollständige visuelle Inspektion des Prüflings aus mehreren Perspektiven ermöglicht und damit den Anforderungen einer industriellen Inline‑Qualitätskontrolle gerecht wird.

Jeder Prüfling wird während des Prüfprozesses synchron aus insgesamt zwölf fest definierten Kameraperspektiven aufgenommen. Die räumliche Anordnung der Kameras ist so gewählt, dass alle funktionsrelevanten Oberflächenbereiche des Steckverbinders, einschließlich Gehäusestrukturen, Kontaktbereiche und Übergangszone zum Kabel, aus unterschiedlichen Blickwinkeln erfasst werden. Pro Bauteil entsteht somit ein strukturierter Satz mehrperspektivischer Einzelbilder, der gemeinsam eine möglichst vollständige visuelle Repräsentation des Produkts abbildet. Diese Multi‑View‑Struktur bildet die zentrale Datenbasis für die in dieser Arbeit betrachteten Anomalieerkennungsverfahren.

Der Datensatz repräsentiert überwiegend den regulären Produktionszustand, da der Großteil der Bilddaten von fehlerfreien Produkten stammt. Reale Schlechtteile sind hingegen nur in begrenztem Umfang verfügbar und decken nicht die vollständige Bandbreite potenzieller Defektarten ab. Diese Eigenschaft ist typisch für industrielle Qualitätsdaten und führt zu einer stark unbalancierten Klassenverteilung, bei der der Normalzustand deutlich überrepräsentiert ist. Entsprechend stehen explizit annotierte Fehlerdaten lediglich in eingeschränktem Umfang zur Verfügung und werden in dieser Arbeit nicht als primäre Trainingsgrundlage genutzt.

Die auftretenden Anomalien weisen eine hohe visuelle Variabilität auf und können sich in unterschiedlichen Formen äußern, beispielsweise durch lokale Materialabweichungen, Verschmutzungen, geometrische Verformungen oder Beschädigungen. Viele dieser Anomalien sind räumlich begrenzt und treten häufig nur in einzelnen Kameraperspektiven auf, während andere Ansichten desselben Prüflings unauffällig erscheinen. Diese Eigenschaft verdeutlicht den potenziellen Mehrwert einer mehrperspektivischen Auswertung, stellt jedoch zugleich erhöhte Anforderungen an die Modellierung des Normalzustands sowie an die Aggregation von Anomaliescores über mehrere Perspektiven hinweg.

Darüber hinaus unterscheiden sich die einzelnen Bildansichten aufgrund der festen Kamerapositionen hinsichtlich Sichtbereich, Abbildungsmaßstab und Detailgrad. Zusätzlich können variationsbedingte Einflüsse auftreten, etwa durch geringfügige Positionsabweichungen des Prüflings oder perspektivabhängige Beleuchtungseffekte. Diese inhärenten Variationen sind im Rahmen der nachfolgenden Vorverarbeitung gezielt zu berücksichtigen, um eine konsistente und vergleichbare Analyse der unterschiedlichen Bildansichten zu ermöglichen.

Der Datensatz wird in dieser Studienarbeit primär zur Untersuchung methodischer Fragestellungen herangezogen. Der Fokus liegt nicht auf der Erzielung absoluter Leistungskennzahlen, sondern auf der Analyse konzeptioneller Zusammenhänge, insbesondere hinsichtlich der Eignung mehrperspektivischer Bilddaten für unsupervised Anomalieerkennungsverfahren. Die Datensatzbeschreibung bildet damit die Grundlage für die im folgenden Abschnitt beschriebenen Schritte der Vorverarbeitung und Normalisierung, die eine zentrale Rolle für die nachfolgende Modellierung und Evaluation einnehmen.

// INSERT DATASET STRUCTURE <TODO>