Die Vorverarbeitung der Bilddaten stellt einen zentralen Bestandteil des Gesamtprozesses der bildbasierten unsupervised Anomaly Detection dar. Insbesondere bei mehrperspektivischen Datensätzen beeinflussen Konsistenz und Strukturierung der Vorverarbeitung maßgeblich die Fähigkeit eines Modells, einen stabilen und generalisierbaren Normalzustand zu erlernen. Ziel der Vorverarbeitung ist es daher, variationsbedingte Einflüsse zu reduzieren und eine vergleichbare Repräsentation der einzelnen Bildansichten sicherzustellen, ohne dabei relevante visuelle Merkmale zu verlieren.

Aufgrund der festen Anordnung der Kameras liegen die einzelnen Perspektiven in unterschiedlichen Bildkoordinatensystemen vor und unterscheiden sich hinsichtlich Sichtbereich, Abbildungsmaßstab und Detailgrad. Die Vorverarbeitung erfolgt daher perspektivweise, wobei jede Kamerasicht separat, jedoch nach einheitlichen Prinzipien behandelt wird. Dieses Vorgehen stellt sicher, dass perspektivbedingte Unterschiede nicht ungewollt die Modellierung des Normalzustands dominieren und gleichzeitig charakteristische Merkmale der jeweiligen Ansicht erhalten bleiben.

Ein grundlegender Schritt der Vorverarbeitung besteht in der Vereinheitlichung der Bildauflösungen und ‑formate entsprechend den Anforderungen der eingesetzten Modelle. Die Bilddaten werden hierzu auf eine definierte Zielauflösung skaliert und in ein konsistentes Farbformat überführt. Diese Schritte orientieren sich an etablierten Vorgehensweisen der bildbasierten Anomalieerkennung und ermöglichen eine vergleichbare Merkmalsextraktion über verschiedene Perspektiven hinweg.

Darüber hinaus wird eine pixelbasierte Normalisierung der Bildintensitäten durchgeführt, um variationsbedingte Einflüsse wie perspektivabhängige Beleuchtungsunterschiede oder kamerabedingte Helligkeitsabweichungen zu reduzieren. Die Normalisierung erfolgt separat pro Perspektive, um systematische Unterschiede zwischen den Kameras auszugleichen. Ziel ist dabei keine vollständige Homogenisierung der Bilddaten, sondern die Schaffung einer stabilen Grundlage für die nachfolgende Merkmalsextraktion und Anomaliebewertung.

Ein weiterer wesentlicher Aspekt der Vorverarbeitung ist die strukturierte Organisation der mehrperspektivischen Daten. Die Einzelbilder eines Prüflings werden als zusammengehörige Einheit behandelt, wobei die Zuordnung der Perspektiven über die gesamte Verarbeitungskette hinweg erhalten bleibt. Diese Strukturierung ist insbesondere für die spätere Aggregation von Anomaliescores über mehrere Ansichten hinweg relevant und ermöglicht sowohl monoperspektivische als auch multiview‑basierte Auswertungsstrategien.

Da der Datensatz überwiegend aus fehlerfreien Bildern besteht, erfolgt im Vorverarbeitungsschritt keine gezielte Selektion oder Entfernung potenzieller Anomalien. Ebenso wird auf eine aggressive Datenbereinigung bewusst verzichtet, um den realen industriellen Charakter der Daten beizubehalten. Ziel ist es, die Bedingungen abzubilden, unter denen das Modell den Normalzustand erlernt und bewertet, und dadurch eine realistische Einschätzung der Robustheit der eingesetzten Verfahren zu ermöglichen.

Die beschriebene Vorverarbeitung bildet die methodische Grundlage für die im folgenden Abschnitt dargestellten Modellierungsansätze. Durch die perspektivkonsistente Normalisierung und strukturierte Organisation der Bilddaten wird sichergestellt, dass Unterschiede in der Anomalieerkennungsleistung primär auf modellseitige Entscheidungen zurückzuführen sind und nicht auf inkonsistente Datenaufbereitung.

// INSERT STEPS <TODO>