Die Implementierung der in dieser Studienarbeit betrachteten Anomalieerkennungsmodelle erfolgt vor dem Hintergrund der zuvor beschriebenen Datencharakteristik sowie der definierten Zielsetzung. Ziel ist nicht die Entwicklung einer produktiven Qualitätsprüflösung, sondern die methodische Analyse und vergleichende Einordnung unterschiedlicher Modellklassen im Kontext der mehrperspektivischen, bildbasierten unsupervised Anomaly Detection. Der Schwerpunkt liegt daher auf konzeptionellen Entscheidungen, der Vergleichbarkeit der Ansätze sowie deren grundsätzlicher Eignung für industrielle Multi‑View‑Szenarien.

Die implementierten Verfahren lassen sich verschiedenen Klassen unsupervised Anomalieerkennungsansätze zuordnen. Gemeinsam ist allen Modellen, dass sie den Normalzustand des Produkts ausschließlich anhand fehlerfreier Bilddaten modellieren und Abweichungen von diesem erlernten Normalverhalten als Anomalien quantifizieren. Unterschiede bestehen insbesondere hinsichtlich der verwendeten Merkmalsextraktion, der Repräsentation des Normalzustands sowie der Berechnung und Aggregation von Anomaliescores.

Ein zentraler Bestandteil der Modellimplementierung ist die tiefenlernbasierte Merkmalsextraktion unter Verwendung vortrainierter Convolutional Neural Networks. Die extrahierten Merkmale dienen nicht der direkten Klassifikation, sondern als kompakte Repräsentationen relevanter visueller Strukturen, anhand derer Abweichungen vom Normalzustand bewertet werden. Der Einsatz vortrainierter Modelle ermöglicht eine robuste Merkmalsextraktion auch bei begrenzter Datenverfügbarkeit und reduziert den Bedarf an aufwändigem modellseitigem Training.

Die Modellierung erfolgt zunächst in einer monoperspektivischen Grundform, bei der jede Kameraperspektive separat verarbeitet wird. Für jede Ansicht wird ein eigenständiger Anomaliescore berechnet, der angibt, inwieweit die jeweilige Perspektive vom erlernten Normalzustand abweicht. Dieses Vorgehen erlaubt eine detaillierte Analyse der einzelnen Kamerasichten und bildet die Grundlage für ein besseres Verständnis perspektivabhängiger Sensitivitäten gegenüber unterschiedlichen Anomaliearten.

Aufbauend auf diesen monoperspektivischen Auswertungen werden verschiedene Strategien zur Nutzung der mehrperspektivischen Informationen betrachtet. Im Fokus stehen hierbei insbesondere späte Fusionsansätze (Late Fusion), bei denen die pro Perspektive berechneten Anomaliescores zu einem Gesamtscore pro Prüfling aggregiert werden. Solche Ansätze ermöglichen eine robuste Gesamtbewertung unter Berücksichtigung aller verfügbaren Ansichten und zeichnen sich durch eine hohe Flexibilität sowie eine vergleichsweise geringe Kopplung der einzelnen Perspektiven aus.

Ergänzend werden frühere Fusionsstrategien (Early Fusion) konzeptionell eingeordnet, bei denen Merkmalsrepräsentationen mehrerer Perspektiven bereits vor der eigentlichen Anomaliebewertung kombiniert werden. Diese Ansätze versprechen eine stärkere Nutzung komplementärer Informationen, gehen jedoch mit erhöhter Modellkomplexität und potenziellen Abhängigkeiten zwischen den Perspektiven einher. Im Rahmen dieser Studienarbeit werden sie daher ausschließlich auf konzeptioneller Ebene betrachtet.

Bei der Implementierung der Modelle wird bewusst auf eine spezifische Anpassung an konkrete Fehlerbilder verzichtet. Es werden keine expliziten Fehlerklassen definiert und keine fehlerbezogenen Hyperparameter optimiert. Ziel ist es vielmehr, die Generalisierungsfähigkeit der Ansätze sowie deren Robustheit gegenüber unbekannten Anomalien zu analysieren. Diese bewusste Abstraktion entspricht dem Charakter der Studienarbeit und ermöglicht eine realistische Bewertung der grundsätzlichen Eignung der betrachteten Modellklassen.

Die implementierten Modelle bilden die Grundlage für die im folgenden Abschnitt dargestellte Evaluation. Dabei steht nicht der direkte Leistungsvergleich einzelner Architekturen im Vordergrund, sondern die systematische Analyse methodischer Unterschiede, insbesondere im Hinblick auf die Nutzung mehrperspektivischer Bildinformationen und deren Einfluss auf die Anomalieerkennung im industriellen Umfeld.

// INSERT MODELCOMPARISON <TODO>